import {
  IconBell,
  IconAdjustmentsHorizontal,
  IconAlertTriangle,
  IconBuilding,
  IconBriefcase,
  IconBulb,
  IconCalendar,
  IconCertificate,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChartBar,
  IconCheck,
  IconClipboardText,
  IconDeviceFloppy,
  IconDownload,
  IconDotsVertical,
  IconEdit,
  IconExternalLink,
  IconFileDescription,
  IconFiles,
  IconFileText,
  IconHelpCircle,
  IconHome,
  IconLayoutGrid,
  IconEye,
  IconEyeOff,
  IconLock,
  IconLoader2,
  IconLogout,
  IconMail,
  IconMapPin,
  IconMaximize,
  IconMinimize,
  IconPhone,
  IconPhoto,
  IconPlus,
  IconPower,
  IconPresentation,
  IconRefresh,
  IconSearch,
  IconSettings,
  IconTargetArrow,
  IconTrash,
  IconUpload,
  IconUser,
  IconUserPlus,
  IconUsers,
  IconUsersGroup,
  IconX,
} from "@tabler/icons-react";

const icons = {
  adjustments: IconAdjustmentsHorizontal,
  alert: IconAlertTriangle,
  bell: IconBell,
  building: IconBuilding,
  briefcase: IconBriefcase,
  bulb: IconBulb,
  calendar: IconCalendar,
  certificate: IconCertificate,
  chevronDown: IconChevronDown,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  chart: IconChartBar,
  check: IconCheck,
  clipboard: IconClipboardText,
  deviceFloppy: IconDeviceFloppy,
  download: IconDownload,
  dots: IconDotsVertical,
  edit: IconEdit,
  externalLink: IconExternalLink,
  fileDescription: IconFileDescription,
  files: IconFiles,
  fileText: IconFileText,
  help: IconHelpCircle,
  home: IconHome,
  grid: IconLayoutGrid,
  eye: IconEye,
  eyeOff: IconEyeOff,
  lock: IconLock,
  loader: IconLoader2,
  logout: IconLogout,
  mail: IconMail,
  mapPin: IconMapPin,
  maximize: IconMaximize,
  minimize: IconMinimize,
  phone: IconPhone,
  photo: IconPhoto,
  plus: IconPlus,
  power: IconPower,
  presentation: IconPresentation,
  refresh: IconRefresh,
  search: IconSearch,
  settings: IconSettings,
  target: IconTargetArrow,
  trash: IconTrash,
  upload: IconUpload,
  user: IconUser,
  userPlus: IconUserPlus,
  users: IconUsers,
  usersGroup: IconUsersGroup,
  x: IconX,
};

export type AppIconName = keyof typeof icons;

type AppIconProps = {
  name: AppIconName;
  size?: number;
  stroke?: number;
  className?: string;
};

export function AppIcon({ name, size = 20, stroke = 1.8, className }: AppIconProps) {
  const Icon = icons[name];
  return <Icon size={size} stroke={stroke} className={className} aria-hidden="true" />;
}
